# Generated by Django 4.1.5 on 2023-08-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=10)),
                ('Middlename', models.CharField(max_length=10)),
                ('Lastname', models.CharField(max_length=10)),
                ('Mobile', models.CharField(max_length=10)),
                ('Adress', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Psw', models.CharField(max_length=20)),
            ],
        ),
    ]
